name = "Gradle"
type = "cli"

[platform.linux]
checksum-file = "gradle-{version}-bin.zip.sha256"
download-file = "gradle-{version}-bin.zip"
archive-prefix = "gradle-{version}"
exe-path = "bin/gradle"

[platform.macos]
checksum-file = "gradle-{version}-bin.zip.sha256"
download-file = "gradle-{version}-bin.zip"
archive-prefix = "gradle-{version}"
exe-path = "bin/gradle"

[platform.windows]
checksum-file = "gradle-{version}-bin.zip.sha256"
download-file = "gradle-{version}-bin.zip"
archive-prefix = "gradle-{version}"
exe-path = "bin/gradle.bat"

[install]
checksum-url = "https://services.gradle.org/distributions/{checksum_file}"
download-url = "https://services.gradle.org/distributions/{download_file}"

[install.exes]
[install.exes.gradle]
primary = true

[resolve]
manifest-url = "https://services.gradle.org/versions/all"
manifest-version-key = "version"
